# NumPy Exercise

In [ ]:

import numpy as np
    

### 1. Array creation and basic operations

In [ ]:

# (1) Create a 10x10 random array with values between 0 and 100 (int)
arr = ...
print(arr)
    

[[90  2 69 42 92 50 80 99 65 10]
 [22 32 67  9 77 61 60  2 23 25]
 [ 9 58  1  8 83 84 25 18 66 60]
 [55 78 29 21 90 91 85 95 12 33]
 [23 74 98 87 55 35 26 63 31 28]
 [70 88 51 30 36 68 27 93 19 85]
 [77  1 75  3 85 63 72 16 88  4]
 [ 9 57 60 26  6 58 43 61 16 17]
 [55 60 35 38  2 14 99 36  0 18]
 [82 55 86 90 97  2 96 16 96 55]]


In [ ]:

# (2) Calculate the minimum, maximum, and mean of the array
min_value = ...    # Minimum value
max_value = ...    # Maximum value
mean_value = ...  # Mean value

print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)
    

Min: 0 Max: 99 Mean: 49.34


In [ ]:

# (3) Compute the sum of the array along rows or columns
row_sum = ...  # Sum along rows
col_sum = ...  # Sum along columns

print("Row sum:", row_sum)
print("Column sum:", col_sum)
    

Row sum: [599 378 412 589 520 567 484 353 357 675]
Column sum: [492 505 571 354 623 526 613 499 416 335]


### 2. Array reshaping and merging

In [ ]:

# (1) Reshape the array into a 5x20 array
reshaped_array = ...
print("Reshaped array:", reshaped_array)
    

Reshaped array: [[90  2 69 42 92 50 80 99 65 10 22 32 67  9 77 61 60  2 23 25]
 [ 9 58  1  8 83 84 25 18 66 60 55 78 29 21 90 91 85 95 12 33]
 [23 74 98 87 55 35 26 63 31 28 70 88 51 30 36 68 27 93 19 85]
 [77  1 75  3 85 63 72 16 88  4  9 57 60 26  6 58 43 61 16 17]
 [55 60 35 38  2 14 99 36  0 18 82 55 86 90 97  2 96 16 96 55]]


In [ ]:

# (2) Create a 1x20 array using np.ones, and concatenate it to the reshaped array along the rows
new_array = ...
concatenated_array = ...
print("Concatenated array:", concatenated_array)
    

Concatenated array: [[90.  2. 69. 42. 92. 50. 80. 99. 65. 10. 22. 32. 67.  9. 77. 61. 60.  2.
  23. 25.]
 [ 9. 58.  1.  8. 83. 84. 25. 18. 66. 60. 55. 78. 29. 21. 90. 91. 85. 95.
  12. 33.]
 [23. 74. 98. 87. 55. 35. 26. 63. 31. 28. 70. 88. 51. 30. 36. 68. 27. 93.
  19. 85.]
 [77.  1. 75.  3. 85. 63. 72. 16. 88.  4.  9. 57. 60. 26.  6. 58. 43. 61.
  16. 17.]
 [55. 60. 35. 38.  2. 14. 99. 36.  0. 18. 82. 55. 86. 90. 97.  2. 96. 16.
  96. 55.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.]]


### 3. Logical operations and filtering

In [ ]:

# (1) Use boolean indexing to find all elements greater than 50, and set them to 50
arr = ...
print("Array after setting elements > 50 to 50:", arr)
    

Array after setting elements > 50 to 50: [[50  2 50 42 50 50 50 50 50 10]
 [22 32 50  9 50 50 50  2 23 25]
 [ 9 50  1  8 50 50 25 18 50 50]
 [50 50 29 21 50 50 50 50 12 33]
 [23 50 50 50 50 35 26 50 31 28]
 [50 50 50 30 36 50 27 50 19 50]
 [50  1 50  3 50 50 50 16 50  4]
 [ 9 50 50 26  6 50 43 50 16 17]
 [50 50 35 38  2 14 50 36  0 18]
 [50 50 50 50 50  2 50 16 50 50]]


In [ ]:

# (2) Find the positions of all even numbers in the array
even_positions = ...
print("Even number positions:", even_positions)
    

Even number positions: [[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [0 6]
 [0 7]
 [0 8]
 [0 9]
 [1 0]
 [1 1]
 [1 2]
 [1 4]
 [1 5]
 [1 6]
 [1 7]
 [2 1]
 [2 3]
 [2 4]
 [2 5]
 [2 7]
 [2 8]
 [2 9]
 [3 0]
 [3 1]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 8]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 6]
 [4 7]
 [4 9]
 [5 0]
 [5 1]
 [5 2]
 [5 3]
 [5 4]
 [5 5]
 [5 7]
 [5 9]
 [6 0]
 [6 2]
 [6 4]
 [6 5]
 [6 6]
 [6 7]
 [6 8]
 [6 9]
 [7 1]
 [7 2]
 [7 3]
 [7 4]
 [7 5]
 [7 7]
 [7 8]
 [8 0]
 [8 1]
 [8 3]
 [8 4]
 [8 5]
 [8 6]
 [8 7]
 [8 8]
 [8 9]
 [9 0]
 [9 1]
 [9 2]
 [9 3]
 [9 4]
 [9 5]
 [9 6]
 [9 7]
 [9 8]
 [9 9]]


### 4. Linear algebra operations

In [ ]:

# (1) Create a 3x3 identity matrix
identity_matrix = ...
print("Identity matrix:", identity_matrix)
    

Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

# (2) Create a 3x3 random matrix and compute its inverse
random_matrix = ...
inv_matrix = ...  # Inverse of the matrix

print("Random matrix:", random_matrix)
print("Inverse matrix:", inv_matrix)
    

Random matrix: [[0.49372687 0.98313143 0.81270872]
 [0.27369507 0.06167916 0.56542312]
 [0.76514223 0.27931762 0.33958755]]
Inverse matrix: [[-0.47221187 -0.36834367  1.74341121]
 [ 1.17093895 -1.56559546 -0.19555614]
 [ 0.100844    2.11766805 -0.82257217]]


In [ ]:

# (3) Matrix multiplication
matrix_product = ...
print("Matrix product (should be close to identity matrix):", matrix_product)
    

Matrix product (should be close to identity matrix): [[ 1.00000000e+00 -7.58922356e-17  1.23627128e-16]
 [ 7.62335439e-18  1.00000000e+00  3.14554139e-17]
 [ 2.23124797e-17  3.33628943e-17  1.00000000e+00]]
